name: Docker Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Permission
      run: chmod +x start_discord
    - name: Build the Docker image
      run: docker build . 
